testmod_task:
  container:
    image: python:3

  setup_script:
    - pip install .
  script:
    - python -m testmod
 
build_task:
  container:
    image: python:3

  setup_script:
    - pip install bork
  script:
    - bork build
 
 test_task:
  container:
    image: python:3

  script:
    - python setup.py test
 